{
 "title": "Mina Node Dashboard",
 "description": "A quickstart to set up a Mina Node Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_exporter_build_info{job=\"mina\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Mina Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Local Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coda_Runtime_process_uptime_ms_total"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Coda_Network_peers" }
   ]
  },
  {
   "title": "Max Observed Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coda_Transition_frontier_max_blocklength_observed"
    }
   ]
  },
  {
   "title": "Block Producer",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coda_Block_producer_blocks_produced",
     "legendFormat": "Blocks Produced"
    },
    { "expr": "Coda_Block_producer_slots_won", "legendFormat": "Slots Won" }
   ]
  },
  {
   "title": "Consensus",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coda_Consensus_stake_delegators",
     "legendFormat": "Delegators"
    },
    {
     "expr": "Coda_Consensus_staking_keypairs",
     "legendFormat": "Staking Keypairs"
    },
    { "expr": "Coda_Consensus_vrf_evaluations", "legendFormat": "VRF Evaluations" }
   ]
  },
  {
   "title": "Max Observed Unvalidated Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coda_Transition_frontier_max_unvalidated_blocklength_observed"
    }
   ]
  },
  {
   "title": "Block Latency Inclusion Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Coda_Block_latency_inclusion_time",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "Block Latency Gossip Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Coda_Block_latency_gossip_time", "legendFormat": "Seconds" }
   ]
  },
  {
   "title": "Block Latency Gossip Slots Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Coda_Block_latency_gossip_slots",
     "legendFormat": "Slots"
    }
   ]
  },
  {
   "title": "Snark Work Fees",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coda_Snark_work_snark_fee_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Snark Fees per Block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coda_Scan_state_snark_fees_per_block"
    }
   ]
  },
  {
   "title": "Transaction Fees Per Block (Mina)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coda_Scan_state_transaction_fees_per_block / 1000000000",
     "legendFormat": "Mina"
    }
   ]
  },
  { "title": "Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  (1 - rate(node_cpu_seconds_total{job=\"mina\", mode=\"idle\", instance=\"$instance\"}[$__interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"mina\", mode=\"idle\", instance=\"$instance\"})\n)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"mina\", instance=\"$instance\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"mina\", instance=\"$instance\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"node\", instance=\"$instance\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"node\", instance=\"$instance\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"mina\", instance=\"$instance\"}\n-\n  node_memory_MemFree_bytes{job=\"mina\", instance=\"$instance\"}\n-\n  node_memory_Buffers_bytes{job=\"mina\", instance=\"$instance\"}\n-\n  node_memory_Cached_bytes{job=\"mina\", instance=\"$instance\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node\", instance=\"$instance\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node\", instance=\"$instance\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node\", instance=\"$instance\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"mina\", instance=\"$instance\"})\n/\n  avg(node_memory_MemTotal_bytes{job=\"mina\", instance=\"$instance\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"mina\", instance=\"$instance\", device!=\"\"}[$__interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"mina\", instance=\"$instance\", device!=\"\"}[$__interval])",
     "legendFormat": "{{device}} written"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"mina\", instance=\"$instance\", device!=\"\"}[$__interval])",
     "legendFormat": "{{device}} io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_size_bytes{job=\"mina\", instance=\"$instance\", fstype!=\"\"}\n  -\n    node_filesystem_avail_bytes{job=\"mina\", instance=\"$instance\", fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "used"
    },
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_avail_bytes{job=\"mina\", instance=\"$instance\", fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"mina\", instance=\"$instance\", device!=\"lo\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"mina\", instance=\"$instance\", device!=\"lo\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}